name: sync_offline_requests
homepage: https://github.com/deeps00007/sync_offline_requests
repository: https://github.com/deeps00007/sync_offline_requests

description: "A Flutter package that provides offline-first HTTP request handling with automatic synchronization when internet connectivity is restored. Requests are safely stored in SQLite and retried with configurable limits."
version: 1.0.3

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # âœ… RUNTIME DEPENDENCIES (MUST BE HERE)
  sqflite: ^2.3.0
  path: ^1.9.0
  http: ^1.2.0
  connectivity_plus: ^5.0.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
